# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='astm_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='uns_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
