# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20170816_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fluid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('specific_gravity', models.FloatField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('units', models.CharField(max_length=40)),
                ('outside_diameter', models.FloatField(max_length=40)),
                ('inside_diameter', models.FloatField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
