# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_fluid_pipesize'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltinSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('systemNumber', models.IntegerField(default=0)),
                ('systemCode', models.CharField(max_length=40)),
            ],
        ),
    ]
