# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_builtinsystem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='builtinsystem',
            old_name='systemCode',
            new_name='system_code',
        ),
        migrations.RenameField(
            model_name='builtinsystem',
            old_name='systemNumber',
            new_name='system_number',
        ),
    ]
