# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20170818_0354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuiltinSystem',
            new_name='System',
        ),
    ]
