# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='points',
            field=models.ManyToManyField(to='data_collection.Point'),
        ),
    ]
