# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0002_run_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='highhigh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='lowlow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='units',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
