# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 18:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_collection', '0003_auto_20170904_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='run',
            name='points',
            field=models.ManyToManyField(blank=True, null=True, to='data_collection.Point'),
        ),
    ]
