# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 23:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_collection', '0005_auto_20170904_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedpoint',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='collectedpoint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectedrun',
            name='collected_points',
            field=models.ManyToManyField(blank=True, null=True, to='data_collection.CollectedPoint'),
        ),
        migrations.AddField(
            model_name='collectedrun',
            name='submitted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='collectedrun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
