# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pidTagPrefix', models.CharField(max_length=5)),
                ('pidTagNum', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pidTagPrefix', models.CharField(max_length=5)),
                ('pidTagNum', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='projectCode',
            field=models.CharField(max_length=12),
        ),
        migrations.AddField(
            model_name='valve',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='valve',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.System'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.System'),
        ),
    ]
