# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170816_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='systemCode',
            field=models.CharField(max_length=40),
        ),
    ]
