# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170816_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='detailedDescription',
            field=models.CharField(default='This is a valve', max_length=255),
        ),
        migrations.AddField(
            model_name='valve',
            name='material',
            field=models.CharField(default='PVC', max_length=40),
        ),
        migrations.AddField(
            model_name='valve',
            name='pipeclass',
            field=models.CharField(default='SOME STRING', max_length=40),
        ),
        migrations.AddField(
            model_name='valve',
            name='size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='valve',
            name='valvemodel',
            field=models.CharField(default='SOME STRING', max_length=40),
        ),
        migrations.AddField(
            model_name='valve',
            name='vendor',
            field=models.CharField(default='SOME STRING', max_length=40),
        ),
    ]
