# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170816_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valve',
            name='size',
            field=models.CharField(default='e.g. 2"', max_length=40),
        ),
    ]
