# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170816_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='pressure',
            field=models.CharField(default='e.g. 80 psig', max_length=40),
        ),
        migrations.AddField(
            model_name='valve',
            name='service',
            field=models.CharField(default='e.g. Concentrated Seawater', max_length=40),
        ),
        migrations.AddField(
            model_name='valve',
            name='temperature',
            field=models.CharField(default='e.g. 80 deg F', max_length=40),
        ),
    ]
