# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170816_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='connection_size',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='detailedDescription',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='fluid',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='high_high_setpoint',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='high_setpoint',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='installtype',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_range_units',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='low_low_setpoint',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='low_setpoint',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='lower_instrument_range',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='lower_process_range',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='material',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='upper_instrument_range',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='upper_process_range',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
