# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20170816_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_voltage',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
