# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20170816_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='detailedDescription',
            new_name='detailed_description',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='pidTagNum',
            new_name='pid_tag_num',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='pidTagPrefix',
            new_name='pid_tag_prefix',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='installtype',
            new_name='process_connection_type',
        ),
        migrations.RenameField(
            model_name='valve',
            old_name='pidTagNum',
            new_name='pid_tag_num',
        ),
        migrations.RenameField(
            model_name='valve',
            old_name='pidTagPrefix',
            new_name='pid_tag_prefix',
        ),
    ]
