# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20170816_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valve',
            old_name='detailedDescription',
            new_name='connection_type',
        ),
        migrations.RenameField(
            model_name='valve',
            old_name='installtype',
            new_name='detailed_description',
        ),
        migrations.RenameField(
            model_name='valve',
            old_name='pipeflangeclass',
            new_name='pipe_flange_class',
        ),
        migrations.RenameField(
            model_name='valve',
            old_name='valvemodel',
            new_name='valve_model',
        ),
    ]
