# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20170816_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectCode',
            field=models.CharField(max_length=40),
        ),
    ]
