# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20170816_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='analog_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='analog_output',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='digital_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='digital_output',
            field=models.BooleanField(default=False),
        ),
    ]
