# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20170816_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pid_tag_prefix', models.CharField(max_length=5)),
                ('pid_tag_num', models.IntegerField(default=1)),
                ('material', models.CharField(blank=True, max_length=40, null=True)),
                ('size', models.CharField(blank=True, max_length=40, null=True)),
                ('connection_type_side_a', models.CharField(blank=True, max_length=40, null=True)),
                ('connection_type_side_b', models.CharField(blank=True, max_length=40, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.System')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pid_tag_prefix', models.CharField(max_length=5)),
                ('pid_tag_num', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.System')),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('pid_tag_prefix', models.CharField(max_length=5)),
                ('pid_tag_num', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.System')),
            ],
        ),
    ]
