# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_pipe_pump_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tank',
            name='material',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
