# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20170816_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='capacity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
