# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20170816_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valve',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Material'),
        ),
    ]
