# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_fluid_pipesize'),
        ('projects', '0020_auto_20170816_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valve',
            name='size',
        ),
        migrations.AddField(
            model_name='valve',
            name='connection_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.PipeSize'),
        ),
        migrations.AddField(
            model_name='valve',
            name='fluid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Fluid'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='connection_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.PipeSize'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='fluid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Fluid'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Material'),
        ),
    ]
