# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20170816_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
