# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_system_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='system',
            name='project',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='system',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='system',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='system',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='system',
        ),
        migrations.RemoveField(
            model_name='valve',
            name='system',
        ),
        migrations.DeleteModel(
            name='System',
        ),
    ]
