# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_fluid_pipesize'),
        ('projects', '0022_auto_20170817_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='analog_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='analog_output',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='connection_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.PipeSize'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='detailed_description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='digital_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='digital_output',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='fluid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Fluid'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='high_high_setpoint',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='high_setpoint',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_range_units',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_voltage',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='low_low_setpoint',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='low_setpoint',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='lower_instrument_range',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='lower_process_range',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Material'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='process_connection_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='upper_instrument_range',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='upper_process_range',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pipe',
            name='connection_type_side_a',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pipe',
            name='connection_type_side_b',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pipe',
            name='material',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pipe',
            name='size',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='capacity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='material',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='connection_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.PipeSize'),
        ),
        migrations.AddField(
            model_name='valve',
            name='connection_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='detailed_description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='fluid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Fluid'),
        ),
        migrations.AddField(
            model_name='valve',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Material'),
        ),
        migrations.AddField(
            model_name='valve',
            name='pipe_flange_class',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='pressure',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='service',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='temperature',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='valve_model',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='vendor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
