# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_builtinsystem'),
        ('projects', '0023_auto_20170818_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.BuiltinSystem'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.BuiltinSystem'),
        ),
        migrations.AddField(
            model_name='projectsystem',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.BuiltinSystem'),
        ),
        migrations.AddField(
            model_name='pump',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.BuiltinSystem'),
        ),
        migrations.AddField(
            model_name='tank',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.BuiltinSystem'),
        ),
        migrations.AddField(
            model_name='valve',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.BuiltinSystem'),
        ),
    ]
