# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20170817_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='brand_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='model_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
