# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20170913_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('detailed_description', models.CharField(blank=True, max_length=60, null=True)),
                ('pid_tag_prefix', models.CharField(max_length=5)),
                ('pid_tag_num', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.System')),
            ],
        ),
        migrations.AlterField(
            model_name='instrument',
            name='detailed_description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='valve',
            name='detailed_description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='valve',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
