# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20170818_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsystem',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectsystem',
            name='system',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='system',
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='system',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='system',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='system',
        ),
        migrations.RemoveField(
            model_name='valve',
            name='system',
        ),
        migrations.DeleteModel(
            name='ProjectSystem',
        ),
    ]
