# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20171005_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Piece of Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
