# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20171006_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowrate', models.FloatField()),
                ('differential_pressure', models.FloatField()),
                ('specific_gravity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('split_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('note', models.CharField(max_length=200)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Pump')),
            ],
        ),
        migrations.CreateModel(
            name='PumpPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_description', models.CharField(max_length=60)),
                ('material_description', models.CharField(max_length=60)),
                ('note', models.CharField(max_length=200)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Pump')),
            ],
        ),
    ]
