# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20170818_1431'),
        ('projects', '0026_auto_20170818_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.System'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.System'),
        ),
        migrations.AddField(
            model_name='pump',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.System'),
        ),
        migrations.AddField(
            model_name='tank',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.System'),
        ),
        migrations.AddField(
            model_name='valve',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.System'),
        ),
    ]
