# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_pumpop_pumppart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumpop',
            name='pump',
        ),
        migrations.AddField(
            model_name='pump',
            name='operating_points',
            field=models.ManyToManyField(to='projects.PumpOP'),
        ),
    ]
