# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20170818_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='analog_input',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='analog_output',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='digital_input',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='digital_output',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='high_high_setpoint',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='high_setpoint',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='low_low_setpoint',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='low_setpoint',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='process_connection_type',
        ),
        migrations.RemoveField(
            model_name='valve',
            name='connection_type',
        ),
    ]
