# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20171009_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='operating_points',
        ),
        migrations.AddField(
            model_name='pumpop',
            name='pump',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Pump'),
            preserve_default=False,
        ),
    ]
