# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_connectiontype'),
        ('projects', '0028_auto_20170818_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='process_connection_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.ConnectionType'),
        ),
        migrations.AddField(
            model_name='valve',
            name='process_connection_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.ConnectionType'),
        ),
    ]
