# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20170818_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pipe',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pump',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tank',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='valve',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
