# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20171009_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpOP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pump',
            name='operating_points',
            field=models.ManyToManyField(to='projects.PumpOP'),
        ),
    ]
