# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20171009_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='operating_points',
        ),
        migrations.DeleteModel(
            name='PumpOP',
        ),
    ]
