# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20171010_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltank',
            name='full_pid_tag_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='full_pid_tag_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
