# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20171010_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='full_pid_tag_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='full_pid_tag_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalinstrument',
            name='full_pid_tag_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalpipe',
            name='full_pid_tag_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalpump',
            name='full_pid_tag_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalvalve',
            name='full_pid_tag_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='full_pid_tag_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pipe',
            name='full_pid_tag_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pump',
            name='full_pid_tag_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='full_pid_tag_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
