# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20171010_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsystem',
            name='project',
        ),
        migrations.RemoveField(
            model_name='system',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='systems',
            field=models.ManyToManyField(to='projects.System'),
        ),
    ]
