# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20171010_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pump_OP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('diff_pressure', models.FloatField(default=0)),
                ('diff_pressure_units', models.CharField(max_length=20)),
                ('flow', models.FloatField(default=0)),
                ('flow_units', models.CharField(max_length=20)),
                ('eff', models.FloatField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='historicalpump',
            name='style',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pump',
            name='style',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalpump',
            name='ops',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.Pump_OP'),
        ),
        migrations.AddField(
            model_name='pump',
            name='ops',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.Pump_OP'),
            preserve_default=False,
        ),
    ]
