# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_auto_20171010_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpump',
            name='ops',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='ops',
        ),
        migrations.AddField(
            model_name='pump_op',
            name='pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Pump'),
        ),
    ]
