# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20171010_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump_op',
            name='diff_pressure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pump_op',
            name='diff_pressure_units',
            field=models.CharField(default='psid', max_length=20),
        ),
        migrations.AlterField(
            model_name='pump_op',
            name='flow',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pump_op',
            name='flow_units',
            field=models.CharField(default='usgpm', max_length=20),
        ),
    ]
