# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20171010_0126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pump_OP',
            new_name='PumpOP',
        ),
    ]
