# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_auto_20171010_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpop',
            name='eff',
            field=models.FloatField(null=True),
        ),
    ]
