# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20171010_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=40)),
                ('standard', models.CharField(max_length=40)),
                ('note', models.CharField(max_length=20)),
                ('pump', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Pump')),
            ],
        ),
    ]
