# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_pumppart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumppart',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pumppart',
            name='material',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pumppart',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pumppart',
            name='standard',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
