# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20171010_0138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PumpOP',
            new_name='PumpOperatingPoint',
        ),
    ]
