# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20171010_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pumper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
