# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0051_auto_20171011_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
                ('original_file_format', models.CharField(blank=True, max_length=35, null=True)),
                ('released_file_format', models.CharField(blank=True, max_length=35, null=True)),
                ('revision_number', models.CharField(max_length=10)),
                ('notes', models.CharField(blank=True, max_length=60, null=True)),
                ('owner', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.DocumentCategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalControlledDocument',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('drawing_title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
                ('original_file_format', models.CharField(blank=True, max_length=35, null=True)),
                ('released_file_format', models.CharField(blank=True, max_length=35, null=True)),
                ('revision_number', models.CharField(max_length=10)),
                ('notes', models.CharField(blank=True, max_length=60, null=True)),
                ('owner', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.DocumentCategory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.Project')),
            ],
            options={
                'verbose_name': 'historical controlled document',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
