# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_auto_20171011_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsystem',
            name='systemNumberString',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='systemNumberString',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
