# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_auto_20171011_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltank',
            name='capacity_units',
            field=models.CharField(default='us gallons', max_length=20),
        ),
        migrations.AddField(
            model_name='tank',
            name='capacity_units',
            field=models.CharField(default='us gallons', max_length=20),
        ),
    ]
