# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_auto_20171013_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvalve',
            name='ready_for_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valve',
            name='ready_for_quote',
            field=models.BooleanField(default=False),
        ),
    ]
