# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_auto_20171013_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=70)),
                ('due_date', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='PumpSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(max_length=2500)),
                ('contacts', models.TextField(blank=True, max_length=750, null=True)),
                ('deliverables', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Deliverable')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Pump')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.System')),
            ],
        ),
    ]
