# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_auto_20171019_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvalve',
            name='procurement_status',
            field=models.CharField(choices=[('sp', 'Specification Underway'), ('qo', 'Quote Requested'), ('qi', 'Received Quote'), ('op', 'Order Placed'), ('in', 'Installed'), ('rn', 'Commissioned')], default='sp', max_length=2),
        ),
        migrations.AddField(
            model_name='valve',
            name='procurement_status',
            field=models.CharField(choices=[('sp', 'Specification Underway'), ('qo', 'Quote Requested'), ('qi', 'Received Quote'), ('op', 'Order Placed'), ('in', 'Installed'), ('rn', 'Commissioned')], default='sp', max_length=2),
        ),
    ]
