# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_deliverable_pumpspecification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumpspecification',
            name='system',
        ),
    ]
