# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_auto_20171120_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['systemNumber']},
        ),
        migrations.AddField(
            model_name='controlleddocument',
            name='share_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontrolleddocument',
            name='share_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
