# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_pumpspecification_doc_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpspecification',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.DocumentCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pumpspecification',
            name='rev_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
