# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_auto_20171016_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumpspecification',
            name='deliverables',
        ),
        migrations.AddField(
            model_name='deliverable',
            name='pump_spec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.PumpSpecification'),
            preserve_default=False,
        ),
    ]
