# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_auto_20171129_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldocumentcategory',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=60),
            preserve_default=False,
        ),
    ]
