# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_historicalpumpspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpumpspecification',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pumpspecification',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
